CREATE TABLE IF NOT EXISTS `games` (
`AppID`                     int             NOT NULL,
`Name`                      varchar(100)    NOT NULL,
`ReleaseDate`               date            DEFAULT NULL,
`Price`                     float           DEFAULT NULL,
`AboutTheGame`              varchar(255)    DEFAULT NULL,
`HeaderImage`               varchar(255)    DEFAULT NULL,
`Positive`                  int             DEFAULT NULL,
`Negative`                  int             DEFAULT NULL,
`AveragePlaytimeForever`    int             DEFAULT NULL,
`AveragePlaytime2W`         int             DEFAULT NULL,
`MedianPlaytimeForever`     int             DEFAULT NULL,
`MedianPlaytime2W`          int             DEFAULT NULL,
`Developers`                varchar(100)    NOT NULL,
`Publishers`                varchar(100)    NOT NULL,
`Categories`                varchar(400)    NOT NULL,
`Genres`                    varchar(255)    NOT NULL,
`Tags`                      varchar(300)    NOT NULL,
PRIMARY KEY(`AppID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Game Dataset';